# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

distance <- function(data_resample, data_base, data_experiment, ancestry) {
    .Call(`_LDAandLDAS_cal`, data_resample, data_base, data_experiment, ancestry)
}

